//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAfip
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAfip.WSAFIPSoap")]
    public interface WSAFIPSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSAfip.personaReturn> getPersonaAsync(string dirProxy, string proxyUser, string proxyPassword, long CUIT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSAfip.CmpResponse> consultaComprobanteAsync(System.DateTime fecha, string metodo, long nroComprobante, int tipoComprobante, string codAutorizacion, long cuitEmisor, double importe, int puntoVenta);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class personaReturn
    {
        
        private metadata metadataField;
        
        private persona personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public metadata metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public persona persona
        {
            get
            {
                return this.personaField;
            }
            set
            {
                this.personaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class metadata
    {
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        private string servidorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified
        {
            get
            {
                return this.fechaHoraFieldSpecified;
            }
            set
            {
                this.fechaHoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string servidor
        {
            get
            {
                return this.servidorField;
            }
            set
            {
                this.servidorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class Err
    {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class Evt
    {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class Obs
    {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class Opcional
    {
        
        private string idField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class CmpDatos
    {
        
        private string cbteModoField;
        
        private long cuitEmisorField;
        
        private int ptoVtaField;
        
        private int cbteTipoField;
        
        private long cbteNroField;
        
        private string cbteFchField;
        
        private double impTotalField;
        
        private string codAutorizacionField;
        
        private string docTipoReceptorField;
        
        private string docNroReceptorField;
        
        private Opcional[] opcionalesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CbteModo
        {
            get
            {
                return this.cbteModoField;
            }
            set
            {
                this.cbteModoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long CuitEmisor
        {
            get
            {
                return this.cuitEmisorField;
            }
            set
            {
                this.cuitEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PtoVta
        {
            get
            {
                return this.ptoVtaField;
            }
            set
            {
                this.ptoVtaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CbteTipo
        {
            get
            {
                return this.cbteTipoField;
            }
            set
            {
                this.cbteTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long CbteNro
        {
            get
            {
                return this.cbteNroField;
            }
            set
            {
                this.cbteNroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CbteFch
        {
            get
            {
                return this.cbteFchField;
            }
            set
            {
                this.cbteFchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double ImpTotal
        {
            get
            {
                return this.impTotalField;
            }
            set
            {
                this.impTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CodAutorizacion
        {
            get
            {
                return this.codAutorizacionField;
            }
            set
            {
                this.codAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DocTipoReceptor
        {
            get
            {
                return this.docTipoReceptorField;
            }
            set
            {
                this.docTipoReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DocNroReceptor
        {
            get
            {
                return this.docNroReceptorField;
            }
            set
            {
                this.docNroReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public Opcional[] Opcionales
        {
            get
            {
                return this.opcionalesField;
            }
            set
            {
                this.opcionalesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios1.afip.gob.ar/wscdc/")]
    public partial class CmpResponse
    {
        
        private CmpDatos cmpRespField;
        
        private string resultadoField;
        
        private Obs[] observacionesField;
        
        private string fchProcesoField;
        
        private Evt[] eventsField;
        
        private Err[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CmpDatos CmpResp
        {
            get
            {
                return this.cmpRespField;
            }
            set
            {
                this.cmpRespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Obs[] Observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FchProceso
        {
            get
            {
                return this.fchProcesoField;
            }
            set
            {
                this.fchProcesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Evt[] Events
        {
            get
            {
                return this.eventsField;
            }
            set
            {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Err[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class telefono
    {
        
        private long numeroField;
        
        private bool numeroFieldSpecified;
        
        private string tipoLineaField;
        
        private string tipoTelefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified
        {
            get
            {
                return this.numeroFieldSpecified;
            }
            set
            {
                this.numeroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoLinea
        {
            get
            {
                return this.tipoLineaField;
            }
            set
            {
                this.tipoLineaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoTelefono
        {
            get
            {
                return this.tipoTelefonoField;
            }
            set
            {
                this.tipoTelefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class relacion
    {
        
        private System.DateTime ffRelacionField;
        
        private bool ffRelacionFieldSpecified;
        
        private System.DateTime ffVencimientoField;
        
        private bool ffVencimientoFieldSpecified;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private long idPersonaAsociadaField;
        
        private bool idPersonaAsociadaFieldSpecified;
        
        private string subtipoRelacionField;
        
        private string tipoRelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime ffRelacion
        {
            get
            {
                return this.ffRelacionField;
            }
            set
            {
                this.ffRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffRelacionSpecified
        {
            get
            {
                return this.ffRelacionFieldSpecified;
            }
            set
            {
                this.ffRelacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime ffVencimiento
        {
            get
            {
                return this.ffVencimientoField;
            }
            set
            {
                this.ffVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffVencimientoSpecified
        {
            get
            {
                return this.ffVencimientoFieldSpecified;
            }
            set
            {
                this.ffVencimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified
        {
            get
            {
                return this.idPersonaFieldSpecified;
            }
            set
            {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idPersonaAsociada
        {
            get
            {
                return this.idPersonaAsociadaField;
            }
            set
            {
                this.idPersonaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaAsociadaSpecified
        {
            get
            {
                return this.idPersonaAsociadaFieldSpecified;
            }
            set
            {
                this.idPersonaAsociadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string subtipoRelacion
        {
            get
            {
                return this.subtipoRelacionField;
            }
            set
            {
                this.subtipoRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoRelacion
        {
            get
            {
                return this.tipoRelacionField;
            }
            set
            {
                this.tipoRelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class regimen
    {
        
        private string descripcionRegimenField;
        
        private int diaPeriodoField;
        
        private bool diaPeriodoFieldSpecified;
        
        private string estadoField;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int idRegimenField;
        
        private bool idRegimenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        private string tipoRegimenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionRegimen
        {
            get
            {
                return this.descripcionRegimenField;
            }
            set
            {
                this.descripcionRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int diaPeriodo
        {
            get
            {
                return this.diaPeriodoField;
            }
            set
            {
                this.diaPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaPeriodoSpecified
        {
            get
            {
                return this.diaPeriodoFieldSpecified;
            }
            set
            {
                this.diaPeriodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idImpuesto
        {
            get
            {
                return this.idImpuestoField;
            }
            set
            {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified
        {
            get
            {
                return this.idImpuestoFieldSpecified;
            }
            set
            {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idRegimen
        {
            get
            {
                return this.idRegimenField;
            }
            set
            {
                this.idRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegimenSpecified
        {
            get
            {
                return this.idRegimenFieldSpecified;
            }
            set
            {
                this.idRegimenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoRegimen
        {
            get
            {
                return this.tipoRegimenField;
            }
            set
            {
                this.tipoRegimenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class impuesto
    {
        
        private string descripcionImpuestoField;
        
        private int diaPeriodoField;
        
        private bool diaPeriodoFieldSpecified;
        
        private string estadoField;
        
        private System.DateTime ffInscripcionField;
        
        private bool ffInscripcionFieldSpecified;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionImpuesto
        {
            get
            {
                return this.descripcionImpuestoField;
            }
            set
            {
                this.descripcionImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int diaPeriodo
        {
            get
            {
                return this.diaPeriodoField;
            }
            set
            {
                this.diaPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaPeriodoSpecified
        {
            get
            {
                return this.diaPeriodoFieldSpecified;
            }
            set
            {
                this.diaPeriodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime ffInscripcion
        {
            get
            {
                return this.ffInscripcionField;
            }
            set
            {
                this.ffInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffInscripcionSpecified
        {
            get
            {
                return this.ffInscripcionFieldSpecified;
            }
            set
            {
                this.ffInscripcionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idImpuesto
        {
            get
            {
                return this.idImpuestoField;
            }
            set
            {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified
        {
            get
            {
                return this.idImpuestoFieldSpecified;
            }
            set
            {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class email
    {
        
        private string direccionField;
        
        private string estadoField;
        
        private string tipoEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoEmail
        {
            get
            {
                return this.tipoEmailField;
            }
            set
            {
                this.tipoEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class domicilio
    {
        
        private string codPostalField;
        
        private string datoAdicionalField;
        
        private string descripcionProvinciaField;
        
        private string direccionField;
        
        private int idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string localidadField;
        
        private int ordenField;
        
        private bool ordenFieldSpecified;
        
        private string tipoDatoAdicionalField;
        
        private string tipoDomicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codPostal
        {
            get
            {
                return this.codPostalField;
            }
            set
            {
                this.codPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string datoAdicional
        {
            get
            {
                return this.datoAdicionalField;
            }
            set
            {
                this.datoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionProvincia
        {
            get
            {
                return this.descripcionProvinciaField;
            }
            set
            {
                this.descripcionProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idProvincia
        {
            get
            {
                return this.idProvinciaField;
            }
            set
            {
                this.idProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified
        {
            get
            {
                return this.idProvinciaFieldSpecified;
            }
            set
            {
                this.idProvinciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified
        {
            get
            {
                return this.ordenFieldSpecified;
            }
            set
            {
                this.ordenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tipoDatoAdicional
        {
            get
            {
                return this.tipoDatoAdicionalField;
            }
            set
            {
                this.tipoDatoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoDomicilio
        {
            get
            {
                return this.tipoDomicilioField;
            }
            set
            {
                this.tipoDomicilioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class dependencia
    {
        
        private string descripcionDependenciaField;
        
        private int idDependenciaField;
        
        private bool idDependenciaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionDependencia
        {
            get
            {
                return this.descripcionDependenciaField;
            }
            set
            {
                this.descripcionDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idDependencia
        {
            get
            {
                return this.idDependenciaField;
            }
            set
            {
                this.idDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDependenciaSpecified
        {
            get
            {
                return this.idDependenciaFieldSpecified;
            }
            set
            {
                this.idDependenciaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class categoria
    {
        
        private string descripcionCategoriaField;
        
        private string estadoField;
        
        private int idCategoriaField;
        
        private bool idCategoriaFieldSpecified;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionCategoria
        {
            get
            {
                return this.descripcionCategoriaField;
            }
            set
            {
                this.descripcionCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCategoria
        {
            get
            {
                return this.idCategoriaField;
            }
            set
            {
                this.idCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified
        {
            get
            {
                return this.idCategoriaFieldSpecified;
            }
            set
            {
                this.idCategoriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idImpuesto
        {
            get
            {
                return this.idImpuestoField;
            }
            set
            {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified
        {
            get
            {
                return this.idImpuestoFieldSpecified;
            }
            set
            {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class actividad
    {
        
        private string descripcionActividadField;
        
        private long idActividadField;
        
        private bool idActividadFieldSpecified;
        
        private int nomencladorField;
        
        private bool nomencladorFieldSpecified;
        
        private int ordenField;
        
        private bool ordenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionActividad
        {
            get
            {
                return this.descripcionActividadField;
            }
            set
            {
                this.descripcionActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long idActividad
        {
            get
            {
                return this.idActividadField;
            }
            set
            {
                this.idActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idActividadSpecified
        {
            get
            {
                return this.idActividadFieldSpecified;
            }
            set
            {
                this.idActividadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int nomenclador
        {
            get
            {
                return this.nomencladorField;
            }
            set
            {
                this.nomencladorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomencladorSpecified
        {
            get
            {
                return this.nomencladorFieldSpecified;
            }
            set
            {
                this.nomencladorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified
        {
            get
            {
                return this.ordenFieldSpecified;
            }
            set
            {
                this.ordenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified
        {
            get
            {
                return this.periodoFieldSpecified;
            }
            set
            {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class persona
    {
        
        private actividad[] actividadField;
        
        private string apellidoField;
        
        private int cantidadSociosEmpresaMonoField;
        
        private bool cantidadSociosEmpresaMonoFieldSpecified;
        
        private categoria[] categoriaField;
        
        private System.Nullable<long>[] claveInactivaAsociadaField;
        
        private dependencia dependenciaField;
        
        private domicilio[] domicilioField;
        
        private email[] emailField;
        
        private string estadoClaveField;
        
        private System.DateTime fechaContratoSocialField;
        
        private bool fechaContratoSocialFieldSpecified;
        
        private System.DateTime fechaFallecimientoField;
        
        private bool fechaFallecimientoFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private System.DateTime fechaJubiladoField;
        
        private bool fechaJubiladoFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private System.DateTime fechaVencimientoMigracionField;
        
        private bool fechaVencimientoMigracionFieldSpecified;
        
        private string formaJuridicaField;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private impuesto[] impuestoField;
        
        private int leyJubilacionField;
        
        private bool leyJubilacionFieldSpecified;
        
        private string localidadInscripcionField;
        
        private int mesCierreField;
        
        private bool mesCierreFieldSpecified;
        
        private string nombreField;
        
        private string numeroDocumentoField;
        
        private long numeroInscripcionField;
        
        private bool numeroInscripcionFieldSpecified;
        
        private string organismoInscripcionField;
        
        private string organismoOriginanteField;
        
        private double porcentajeCapitalNacionalField;
        
        private bool porcentajeCapitalNacionalFieldSpecified;
        
        private string provinciaInscripcionField;
        
        private string razonSocialField;
        
        private regimen[] regimenField;
        
        private relacion[] relacionField;
        
        private string sexoField;
        
        private telefono[] telefonoField;
        
        private string tipoClaveField;
        
        private string tipoDocumentoField;
        
        private string tipoOrganismoOriginanteField;
        
        private string tipoPersonaField;
        
        private string tipoResidenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividad[] actividad
        {
            get
            {
                return this.actividadField;
            }
            set
            {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cantidadSociosEmpresaMono
        {
            get
            {
                return this.cantidadSociosEmpresaMonoField;
            }
            set
            {
                this.cantidadSociosEmpresaMonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSociosEmpresaMonoSpecified
        {
            get
            {
                return this.cantidadSociosEmpresaMonoFieldSpecified;
            }
            set
            {
                this.cantidadSociosEmpresaMonoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categoria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public categoria[] categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("claveInactivaAsociada", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<long>[] claveInactivaAsociada
        {
            get
            {
                return this.claveInactivaAsociadaField;
            }
            set
            {
                this.claveInactivaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public dependencia dependencia
        {
            get
            {
                return this.dependenciaField;
            }
            set
            {
                this.dependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("domicilio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public domicilio[] domicilio
        {
            get
            {
                return this.domicilioField;
            }
            set
            {
                this.domicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public email[] email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string estadoClave
        {
            get
            {
                return this.estadoClaveField;
            }
            set
            {
                this.estadoClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime fechaContratoSocial
        {
            get
            {
                return this.fechaContratoSocialField;
            }
            set
            {
                this.fechaContratoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoSocialSpecified
        {
            get
            {
                return this.fechaContratoSocialFieldSpecified;
            }
            set
            {
                this.fechaContratoSocialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime fechaFallecimiento
        {
            get
            {
                return this.fechaFallecimientoField;
            }
            set
            {
                this.fechaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFallecimientoSpecified
        {
            get
            {
                return this.fechaFallecimientoFieldSpecified;
            }
            set
            {
                this.fechaFallecimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime fechaInscripcion
        {
            get
            {
                return this.fechaInscripcionField;
            }
            set
            {
                this.fechaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified
        {
            get
            {
                return this.fechaInscripcionFieldSpecified;
            }
            set
            {
                this.fechaInscripcionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public System.DateTime fechaJubilado
        {
            get
            {
                return this.fechaJubiladoField;
            }
            set
            {
                this.fechaJubiladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaJubiladoSpecified
        {
            get
            {
                return this.fechaJubiladoFieldSpecified;
            }
            set
            {
                this.fechaJubiladoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified
        {
            get
            {
                return this.fechaNacimientoFieldSpecified;
            }
            set
            {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime fechaVencimientoMigracion
        {
            get
            {
                return this.fechaVencimientoMigracionField;
            }
            set
            {
                this.fechaVencimientoMigracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoMigracionSpecified
        {
            get
            {
                return this.fechaVencimientoMigracionFieldSpecified;
            }
            set
            {
                this.fechaVencimientoMigracionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string formaJuridica
        {
            get
            {
                return this.formaJuridicaField;
            }
            set
            {
                this.formaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public long idPersona
        {
            get
            {
                return this.idPersonaField;
            }
            set
            {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified
        {
            get
            {
                return this.idPersonaFieldSpecified;
            }
            set
            {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public impuesto[] impuesto
        {
            get
            {
                return this.impuestoField;
            }
            set
            {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int leyJubilacion
        {
            get
            {
                return this.leyJubilacionField;
            }
            set
            {
                this.leyJubilacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leyJubilacionSpecified
        {
            get
            {
                return this.leyJubilacionFieldSpecified;
            }
            set
            {
                this.leyJubilacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string localidadInscripcion
        {
            get
            {
                return this.localidadInscripcionField;
            }
            set
            {
                this.localidadInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int mesCierre
        {
            get
            {
                return this.mesCierreField;
            }
            set
            {
                this.mesCierreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesCierreSpecified
        {
            get
            {
                return this.mesCierreFieldSpecified;
            }
            set
            {
                this.mesCierreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public long numeroInscripcion
        {
            get
            {
                return this.numeroInscripcionField;
            }
            set
            {
                this.numeroInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroInscripcionSpecified
        {
            get
            {
                return this.numeroInscripcionFieldSpecified;
            }
            set
            {
                this.numeroInscripcionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string organismoInscripcion
        {
            get
            {
                return this.organismoInscripcionField;
            }
            set
            {
                this.organismoInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string organismoOriginante
        {
            get
            {
                return this.organismoOriginanteField;
            }
            set
            {
                this.organismoOriginanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public double porcentajeCapitalNacional
        {
            get
            {
                return this.porcentajeCapitalNacionalField;
            }
            set
            {
                this.porcentajeCapitalNacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool porcentajeCapitalNacionalSpecified
        {
            get
            {
                return this.porcentajeCapitalNacionalFieldSpecified;
            }
            set
            {
                this.porcentajeCapitalNacionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string provinciaInscripcion
        {
            get
            {
                return this.provinciaInscripcionField;
            }
            set
            {
                this.provinciaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string razonSocial
        {
            get
            {
                return this.razonSocialField;
            }
            set
            {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regimen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public regimen[] regimen
        {
            get
            {
                return this.regimenField;
            }
            set
            {
                this.regimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=30)]
        public relacion[] relacion
        {
            get
            {
                return this.relacionField;
            }
            set
            {
                this.relacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefono", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=32)]
        public telefono[] telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string tipoClave
        {
            get
            {
                return this.tipoClaveField;
            }
            set
            {
                this.tipoClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string tipoOrganismoOriginante
        {
            get
            {
                return this.tipoOrganismoOriginanteField;
            }
            set
            {
                this.tipoOrganismoOriginanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string tipoPersona
        {
            get
            {
                return this.tipoPersonaField;
            }
            set
            {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string tipoResidencia
        {
            get
            {
                return this.tipoResidenciaField;
            }
            set
            {
                this.tipoResidenciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WSAFIPSoapChannel : WSAfip.WSAFIPSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WSAFIPSoapClient : System.ServiceModel.ClientBase<WSAfip.WSAFIPSoap>, WSAfip.WSAFIPSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSAFIPSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSAFIPSoapClient.GetBindingForEndpoint(endpointConfiguration), WSAFIPSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSAFIPSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSAFIPSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSAFIPSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSAFIPSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSAFIPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WSAfip.personaReturn> getPersonaAsync(string dirProxy, string proxyUser, string proxyPassword, long CUIT)
        {
            return base.Channel.getPersonaAsync(dirProxy, proxyUser, proxyPassword, CUIT);
        }
        
        public System.Threading.Tasks.Task<WSAfip.CmpResponse> consultaComprobanteAsync(System.DateTime fecha, string metodo, long nroComprobante, int tipoComprobante, string codAutorizacion, long cuitEmisor, double importe, int puntoVenta)
        {
            return base.Channel.consultaComprobanteAsync(fecha, metodo, nroComprobante, tipoComprobante, codAutorizacion, cuitEmisor, importe, puntoVenta);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSAFIPSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSAFIPSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSAFIPSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.0.200/WSAfip/WSAFIP.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSAFIPSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.0.200/WSAfip/WSAFIP.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSAFIPSoap,
            
            WSAFIPSoap12,
        }
    }
}
